### ISSUE TITLE
Stateless function components?

### ISSUE THREAD

**Issue by dimaip** [PackageFactory/PackageFactory.Guevara#14]
I think most of React components here could be simplified to use the new stateless function component way. Wdyt?

**Comment by Inkdpixels** [comment]
Yeah, totally, we will convert them once we have a complete understanding of what each component will do in the future, if it has it's own state or not etc.

So it is on our ToDo-List! :) :+1:

**Comment by Inkdpixels** [comment]
Remaining components:
* DropDown
* I18n
* Portal
* ToggablePanel
* Tree

As well as some of the components in the `Containers` folder.
