### ISSUE TITLE
Integrate redux-actions, Move all redux stuff into one folder `redux`

### ISSUE THREAD

**Issue by Inkdpixels** [PackageFactory/PackageFactory.Guevara#17]
As suggested by @dimaip and me. We both think this makes sense. Maybe we can integrate this on the same step as moving all the redux stuff into one folder named `redux`?

https://github.com/acdlite/redux-actions

What do you think @grebaldi

**Comment by dimaip** [comment]
:+1:

**Comment by Inkdpixels** [comment]
Hey @dimaip - Redux-Actions is now in the stack, you may want to take a look at the changes and give feedback if you want to. Don't mind me closing this issue already, its just for the overall overview of issues here. :) :+1:

**Comment by dimaip** [comment]
Looks good! :+1:
