### ISSUE TITLE
Don't `dispatch` directly from components

### ISSUE THREAD

**Issue by dimaip** [PackageFactory/PackageFactory.Guevara#23]
If we use `react-redux`, it's considered a best practice to not to couple React components with Redux state logic like dispatch, React component should not be aware of the existence of Redux at all.

`connect` method from react-redux package receives second argument that maps array of callbacks to Redux action creators. So the component just exposes some callback and react-redux does the rest.
See https://github.com/rackt/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

**Comment by Inkdpixels** [comment]
:+1:

**Comment by dimaip** [comment]
My description was not really correct. Just read that link and also this could be useful: http://rackt.org/redux/docs/api/bindActionCreators.html
