### ISSUE TITLE
Decouple the development of the UI package from the Neos backend services

### ISSUE THREAD

**Issue by Inkdpixels** [PackageFactory/PackageFactory.Guevara#34]
We should strive into a development workflow where we just run a simple Node.js based server for development purposes. 

The benefits for this will not only be an server we could actually use in our testing stack, but it would also increase the standalone nature of the UI package, basically we are 100% independent while developing. 

The server itself should at least provide the basic endpoints for saving/fetch data, as well as the initial rendering of the app. I don't want to replicate the whole service, but we definitely need a dummy server for testing the UI anyway, so why not also use the server as a development tool too? :)

**Comment by dimaip** [comment]
I can imagine it would be useful not only for development purposes. E.g. if the main php server does not support nodejs, I could run the UI from a completely different machine, perhaps even located on some intranet for security reasons.

**Comment by grebaldi** [comment]
How would we replicate the guest frame then? Everything in there strongly depends on TypoScript/Fluid rendering. Would be a pretty complex thing to mock...

**Comment by Inkdpixels** [comment]
I will close this, since we already got a running flow instance on the CI servers anyway and the effort to create a dummy / full replacement for the services seem to huge for now.
