### ISSUE TITLE
Revisit the end to end tests with selenium

### ISSUE THREAD

**Issue by Inkdpixels** [PackageFactory/PackageFactory.Guevara#57]
In e2f14ab4c69a34ab51ca24c814a23c22ab1525b3 I've removed all selenium related user stories and the build setup, since it was unreliable. This issue is just a reminder to re-visit this whole topic again later on. Maybe a switch to [nightwatch.js](http://nightwatchjs.org/) or [nightmare.js](http://www.nightmarejs.org/) could give us the expected stability?

**Comment by GerDner** [comment]
#84 got merged
