### ISSUE TITLE
Code formatting (.editorconfig) and IDE/Editor-Setup

### ISSUE THREAD

**Issue by GerDner** [PackageFactory/PackageFactory.Guevara#91]
Edit http://flowframework.readthedocs.org/en/stable/TheDefinitiveGuide/PartV/CodingGuideLines/JavaScript.html

Setups for Atom / Webstorm / PHPStorm
 * Packages
 * editorconfig support

**Comment by ryzy** [comment]
I suggest we set 

```
indent_style = space
indent_size = 4
```
globally, for all files (as this seems to be our primary style) and define exceptions for the rest.
And that's what I did in PR #119

@GerDner do you think we should do sth else to resolve this ticket?

**Comment by ryzy** [comment]
BTW I also added `trim_trailing_whitespace = true` which I think makes sense (apart of .md of course).

**Comment by GerDner** [comment]
We could add a jsconfig.json for Visual Studio Code and add Docs for Atom / PHPStorm (extensions etc.)

**Comment by ryzy** [comment]
Thanks, jsconfig added

Don't know what you meant by 'Docs for Atom' - can you supply me with some link? ;)

**Comment by GerDner** [comment]
I think it's a seperate issue. I want to provide a list of modules/extensions for common IDEs/Editors.
Things like JSX-Highlighter/Linter/Autocomplete etc.

**Comment by ryzy** [comment]
I see. As you say, we could supply it later on.

Though, in WebStorm/PhpStorm code completion and JSX syntax is already working pretty well with what we have already here.

**Comment by ryzy** [comment]
Guys, I added another commit to this PR with tiny fixes in PHP code formatting.

Is it OK to have it here? Or shall it go to separate PR?

Shall we merge it? Or sth else needs to be improved?

**Comment by GerDner** [comment]
+1 by reading - i think we can merge this!
