### ISSUE TITLE
Image cropping library

### ISSUE THREAD

**Issue by mstruebing** [PackageFactory/PackageFactory.Guevara#95]
I've found three librarys which can be used for the image cropping feature.

[react-image-crop](https://github.com/DominicTobias/react-image-crop)
[react-cropper](https://github.com/roadmanfong/react-cropper)
[react-avatar-editor](https://github.com/mosch/react-avatar-editor)

**Comment by grebaldi** [comment]
Thanks, @mstruebing! These look pretty awesome :)

Currently I would say, I'm in favor of the first one.

\cc @skurfuerst

**Comment by skurfuerst** [comment]
Thanks a lot :)

**Comment by skurfuerst** [comment]
FYI: Inside https://github.com/PackageFactory/PackageFactory.Guevara/pull/78 I am using the first of the links. Seems to work quite well.
